### ISSUE TITLE
Deleting Stale and Unused Branches

### ISSUE THREAD

**Issue by elisoncrum** [marinecoders/marinecoders.github.io#104]
## Summary
Confirming below branches are stale and good for my to remove from the repository. Doing this in order to clean up repository.

Seeking confirmation from @SemperRuminare @drewhutcheon 

## Branches
[events-page](https://github.com/marinecoders/marinecoders.github.io/tree/events-page)
Updated 2 years ago by [drewhutcheon](https://github.com/drewhutcheon)

[feat-add-subscription](https://github.com/marinecoders/marinecoders.github.io/tree/feat-add-subscription)
Updated 2 years ago by [drewhutcheon](https://github.com/drewhutcheon)

[drewhutcheon-patch-3](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-3)
Updated 2 years ago by [drewhutcheon](https://github.com/drewhutcheon)

[drewhutcheon-patch-8](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-8)
Updated 2 years ago by [drewhutcheon](https://github.com/drewhutcheon)

[drewhutcheon-NDAA-Post](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-NDAA-Post)
Updated 17 months ago by [SemperRuminare](https://github.com/SemperRuminare)

[SemperRuminare-patch-1](https://github.com/marinecoders/marinecoders.github.io/tree/SemperRuminare-patch-1)
Updated 17 months ago by [SemperRuminare](https://github.com/SemperRuminare)

[SemperRuminare-patch-3](https://github.com/marinecoders/marinecoders.github.io/tree/SemperRuminare-patch-3)
Updated 17 months ago by [SemperRuminare](https://github.com/SemperRuminare)

[SemperRuminare-patch-4](https://github.com/marinecoders/marinecoders.github.io/tree/SemperRuminare-patch-4)
Updated 17 months ago by [SemperRuminare](https://github.com/SemperRuminare)

[hat_trick_events_changes_Feb2021](https://github.com/marinecoders/marinecoders.github.io/tree/hat_trick_events_changes_Feb2021)
Updated 17 months ago by [devinsmiley](https://github.com/devinsmiley)

[devinsmiley-patch-1](https://github.com/marinecoders/marinecoders.github.io/tree/devinsmiley-patch-1)
Updated 17 months ago by [devinsmiley](https://github.com/devinsmiley)

[devinsmiley-patch-2](https://github.com/marinecoders/marinecoders.github.io/tree/devinsmiley-patch-2)
Updated 17 months ago by [devinsmiley](https://github.com/devinsmiley)

[drewhutcheon-II-MIG-Cell-Post](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-II-MIG-Cell-Post)
Updated 17 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[drewhutcheon-patch-4](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-4)
Updated 17 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[SemperRuminare-patch-2](https://github.com/marinecoders/marinecoders.github.io/tree/SemperRuminare-patch-2)
Updated 17 months ago by [SemperRuminare](https://github.com/SemperRuminare)

[SemperRuminare-patch-5](https://github.com/marinecoders/marinecoders.github.io/tree/SemperRuminare-patch-5)
Updated 17 months ago by [SemperRuminare](https://github.com/SemperRuminare)

[drewhutcheon-patch-5](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-5)
Updated 17 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[devinsmiley-patch-3](https://github.com/marinecoders/marinecoders.github.io/tree/devinsmiley-patch-3)
Updated 17 months ago by [devinsmiley](https://github.com/devinsmiley)

[devinsmiley-patch-4](https://github.com/marinecoders/marinecoders.github.io/tree/devinsmiley-patch-4)
Updated 16 months ago by [devinsmiley](https://github.com/devinsmiley)

[drewhutcheon-Chat_Link_Updates](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-Chat_Link_Updates)
Updated 16 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[drewhutcheon-patch-6](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-6)
Updated 16 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[images](https://github.com/marinecoders/marinecoders.github.io/tree/images)
Updated 16 months ago by Collin

[lit-patch-1](https://github.com/marinecoders/marinecoders.github.io/tree/lit-patch-1)
Updated 16 months ago by [phansiri](https://github.com/phansiri)

[SemperRuminare-patch-6](https://github.com/marinecoders/marinecoders.github.io/tree/SemperRuminare-patch-6)
Updated 16 months ago by [SemperRuminare](https://github.com/SemperRuminare)

[drewhutcheon-patch-2](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-2)
Updated 15 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[drewhutcheon-patch-1](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-1)
Updated 15 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[devinsmiley-patch-5](https://github.com/marinecoders/marinecoders.github.io/tree/devinsmiley-patch-5)
Updated 15 months ago by [devinsmiley](https://github.com/devinsmiley)

[drewhutcheon-patch-7](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-7)
Updated 15 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[drewhutcheon-patch-9](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-9)
Updated 14 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[drewhutcheon-patch-10](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-10)
Updated 14 months ago by [devinsmiley](https://github.com/devinsmiley)

[drewhutcheon-patch-11](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-11)
Updated 14 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[devinsmiley-patch-6](https://github.com/marinecoders/marinecoders.github.io/tree/devinsmiley-patch-6)
Updated 14 months ago by [devinsmiley](https://github.com/devinsmiley)

[drewhutcheon-patch-12](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-12)
Updated 14 months ago by [drewhutcheon](https://github.com/drewhutcheon)

[newchat](https://github.com/marinecoders/marinecoders.github.io/tree/newchat)
Updated 8 months ago by Collin

[drewhutcheon-patch-15](https://github.com/marinecoders/marinecoders.github.io/tree/drewhutcheon-patch-15)
Updated 8 months ago by [drewhutcheon](https://github.com/drewhutcheon)

**Comment by SemperRuminare** [comment]
Yup no need to keep those around
