### ISSUE TITLE
FEATURE: Input Project Proposal

### ISSUE THREAD

**Issue by drewhutcheon** [marinecoders/marinecoders.github.io#22]

**Comment by drewhutcheon** [comment]
1. Create Github account
2.  Join Marine Coders repo
3. Submit Project Proposal as an "issue"
thoguhts?

**Comment by devinsmiley** [comment]
4. Change button label from "+ give feedback" to "Submit project idea" (if able) on UserReport.

**Comment by SemperRuminare** [comment]
> 1. Change button label from "+ give feedback" to "Submit project idea" (if able) on UserReport.

Haven't been able to find if this is possible. Probably could roll custom js/html from UserReport, not sure if how they're validating input if at all

**Comment by SemperRuminare** [comment]
Added UserReport script on projects page. Could add this to the whole website if we want, but I kind of like it on just that page
