### ISSUE TITLE
FEATURE: Subscription

### ISSUE THREAD

**Issue by drewhutcheon** [marinecoders/marinecoders.github.io#23]
Hutch and Victor
[  ] Make Subscription more visible.
[  ] Add organization, role, and affiliation to Google form (or other)
[  ] Fix "Join Button" link (Says coming soon right now, need instructions here)

**Comment by SemperRuminare** [comment]
Might be able to use govdelivery in a post googleform/surveymonkey world

**Comment by SemperRuminare** [comment]
Added mailchimp!
