### ISSUE TITLE
'Ndaa' should be 'NDAA' on Marine Coders home page

### ISSUE THREAD

**Issue by devinsmiley** [marinecoders/marinecoders.github.io#52]
NDAA blog post title on the homepage shows up as 'Ndaa.' Should show up as 'NDAA.'
<img width="758" alt="Screen Shot 2021-02-10 at 7 31 01 PM" src="https://user-images.githubusercontent.com/13993478/107590643-a3c98b00-6bd6-11eb-9d37-5b0344e608ef.png">

**Comment by SemperRuminare** [comment]
This is due to jekyll automatically converting titles. Here's a post on how to fix - basically we need to add a plugin for jekyll to change capitalization rules.
https://stackoverflow.com/questions/37975716/in-jekyll-how-to-change-the-capitalization-rules-for-converting-a-file-name-int

**Comment by devinsmiley** [comment]
Those kind of 'quick fixes' rarely end up being quick for me. More exploring though!

**Comment by SemperRuminare** [comment]
It looks like the method titlized slug splits the title from the file name, and then capitalizes every word, if we override the method then we can not autocapitalize

**Comment by devinsmiley** [comment]
There should be a way to default so the entire blog post title is capitalized. That way we don't have to mess around with lowercase/camelcase nonstandard rules.

Maybe
`module Jekyll
  module Utils
    def titleize_slug(slug)
      slug.split(/[_-]/).join('').capitalize   #remove space from the join
    end
  end
end`

**Comment by SemperRuminare** [comment]
So are you saying in the following examples:

.md title -> Output

HELLO WORLD -> HELLO WORLD
hello world -> HELLO WORLD
Hello World -> HELLO WORLD

**Comment by devinsmiley** [comment]
Yes

**Comment by SemperRuminare** [comment]
So I just notice that I think title is overriden when you add a title section. I've created a MR but I want to test locally first
https://github.com/marinecoders/marinecoders.github.io/blob/master/_posts/2020-09-30-NavalLetterHackathon2.md

https://github.com/marinecoders/marinecoders.github.io/pull/53

**Comment by SemperRuminare** [comment]
![image](https://user-images.githubusercontent.com/2375683/107648638-91893480-6c4a-11eb-854b-7e21cd0fd958.png)

It works. Please merge: https://github.com/marinecoders/marinecoders.github.io/pull/53

**Comment by SemperRuminare** [comment]
Reopening until @drewhutcheon merges
