### ISSUE TITLE
Post Titles still not displaying correctly.

### ISSUE THREAD

**Issue by devinsmiley** [marinecoders/marinecoders.github.io#61]
@SemperRuminare the II MIG post title is still not displaying correctly. It's the capitalization issue resurfacing. Displays as 'Ii Mig' rather than 'II MIG'

**Comment by SemperRuminare** [comment]
This is user error, please add title block. Closing

![image](https://user-images.githubusercontent.com/2375683/107703974-80f8ae80-6c8a-11eb-94a0-16937d6015a1.png)
